run: shop barber customer
	./shop

shop: shop.c
	gcc -g -Wall -o shop shop.c

barber: barber.c
	gcc -g -Wall -o barber barber.c

customer: customer.c
	gcc -g -Wall -o customer customer.c

clean:
	rm customer barber shop